

          GIFEXE, GIFCLIP, GIFSIZE, GIFWARP, HCPLAY/HCMAKE

                     Shareware Donation Form

All donations must be prepaid, in U.S. funds drawn on a U.S. bank,
or in Canadian funds, drawn on a Canadian bank, or U.S. or Canadian
Money Order, (or Canadian or U.S. Cash, if you accept responsibility
for possible loss...)  Your software will be sent airmail within 5
working days after receipt of payment.  (Canadian funds are accepted
at an exchange rate of $1.25 Canadian dollars per $1.00 U.S. dollar.)
Commercial or Educational users should contact me for licensing
information.  (All prices are minimum suggested donations - Please
feel free to send more - my mother needs an operation ;-) 

Please send me the latest registered version(s) of the following
software:

     Name ______________________________________________________

     Address ___________________________________________________

     ___________________________________________________________

     ___________________________________________________________

     For my information, what brand of Graphics card

     do you have? ______________________________________________


     Suggestions - I just LOVE your software, but I'd be willing

     to pay _______ towards your mothers operation, if it would 

     also ______________________________________________________

     ___________________________________________________________

     ___________________________________________________________

     ___________________________________________________________


     Quantity   Title                       Price/Copy   Total

     ____       GIFEXE                       $8.00 U.S.  _______

     ____       GIFCLIP                      $8.00 U.S.  _______

     ____       GIFSIZE                      $8.00 U.S.  _______

     ____       GIFWARP                      $8.00 U.S.  _______

     ____       HCPLAY/HCMAKE/HCSHOW        $30.00 U.S.  _______

     ____       GIFEXE Package              $23.00 U.S.  _______
                ($9.00 discount
                for all four GIF* programs)

     ____       GIFEXE/HCPLAY Package       $50.00 U.S.  _______
                ($12.00 discount
                for all four GIF* programs
                and HCPLAY/HCMAKE programs

                3.5" Disk (default is 5.25") $2.00 U.S.  _______

                                      Total enclosed     _______


Send your shareware donation to:

        Steve Enns
        44 Macdermid Cres.     Synergrafix Consulting
        Saskatoon, Sk.         Custom Software
        Canada  S7J 2R2        Hardware and Software Consultation

